# Define comprehensive marine regions with bounding boxes or lists of bounding boxes
new_regions = {
    # Global regions
    "worldwide": {"bounds": (-180, -90, 180, 90), "type": "global"},
    "global": {"bounds": (-180, -90, 180, 90), "type": "global"},
    "all oceans": {"bounds": (-180, -90, 180, 90), "type": "global"},

    # Latitudinal zones
    "tropical": {"bounds": (-180, -23.5, 180, 23.5), "type": "latitudinal"},
    "equatorial": {"bounds": (-180, -10, 180, 10), "type": "latitudinal"},
    "temperate": {"bounds": [(-180, 23.5, 180, 66.5), (-180, -66.5, 180, -23.5)], "type": "latitudinal"},
    "polar": {"bounds": [(-180, 66.5, 180, 90), (-180, -90, 180, -66.5)], "type": "latitudinal"},
    "arctic": {"bounds": (-180, 66.5, 180, 90), "type": "latitudinal"},
    "antarctic": {"bounds": (-180, -90, 180, -66.5), "type": "latitudinal"},

    # Ocean basins
    "pacific": {"bounds": (-180, -90, -60, 90), "type": "ocean"},
    "atlantic": {"bounds": (-80, -90, 20, 90), "type": "ocean"},
    "indian": {"bounds": (20, -90, 150, 30), "type": "ocean"},
    "southern ocean": {"bounds": (-180, -90, 180, -60), "type": "ocean"},
    "arctic ocean": {"bounds": (-180, 66.5, 180, 90), "type": "ocean"},
    "western atlantic": {"bounds": (-80, -30, -40, 45), "type": "ocean"},
    "eastern atlantic": {"bounds": (-30, 20, -40, 45), "type": "ocean"},
    "indo pacific": {"bounds": (40, 180, -40, 30), "type": "ocean"},
    "western indian_ocean": {"bounds": (30, 80, -40, 20), "type": "ocean"},
    "eastern indian_ocean": {"bounds": (80, 120, -40, 20), "type": "ocean"},
    "southern ocean": {"bounds": (-180, 180, -90, -50), "type": "ocean"},
    "arctic ocean": {"bounds": (-180, 180, 66, 90), "type": "ocean"},
    "mediterranean sea": {"bounds": (-6, 36, 30, 46), "type": "region"},
    "caribbean sea": {"bounds": (-90, -60, 10, 25), "type": "region"},
    "red sea": {"bounds": (32, 44, 12, 30), "type": "region"},

    # Indo-Pacific regions
    "indo-pacific": {"bounds": [ (20, -50, 180, 30), (-180, -15, 20, 15) ], "type": "regional"},
    "western pacific": {"bounds": (120, -50, 180, 50), "type": "regional"},
    "eastern pacific": {"bounds": (-180, -50, -80, 50), "type": "regional"},
    "central pacific": {"bounds": (-180, -30, -120, 30), "type": "regional"},
    "northwest_pacific": {"bounds": (120, 180, 0, 60), "type": "ocean"},
    "southwest_pacific": {"bounds": (120, 180, -60, 0), "type": "ocean"},

    # Continental regions - Australia
    "australian": {"bounds": (110, -45, 155, -10), "type": "continental"},
    "southern australia": {"bounds": (115, -45, 150, -33), "type": "continental"},
    "northern australia": {"bounds": (110, -25, 155, -10), "type": "continental"},
    "western australia": {"bounds": (110, -35, 125, -15), "type": "continental"},
    "eastern australia": {"bounds": (145, -38, 155, -10), "type": "continental"},
    "southeastern australia": {"bounds": (145, -45, 155, -33), "type": "continental"},
    "southwestern australia": {"bounds": (110, -45, 125, -30), "type": "continental"},
    "northeastern australia": {"bounds": (140, -25, 155, -10), "type": "continental"},
    "northwestern australia": {"bounds": (110, -25, 125, -12), "type": "continental"},

    # Other continental regions
    "north america": {"bounds": (-170, 25, -50, 70), "type": "continental"},
    "south america": {"bounds": (-85, -55, -35, 15), "type": "continental"},
    "europe": {"bounds": (-25, 35, 45, 75), "type": "continental"},
    "africa": {"bounds": (-20, -35, 55, 40), "type": "continental"},
    "asia": {"bounds": (25, -10, 180, 75), "type": "continental"},

    # Regional seas and water bodies
    "mediterranean": {"bounds": (-6, 30, 37, 47), "type": "sea"},
    "red sea": {"bounds": (32, 12, 44, 30), "type": "sea"},
    "persian gulf": {"bounds": (47, 24, 57, 31), "type": "sea"},
    "gulf of mexico": {"bounds": (-98, 18, -80, 31), "type": "sea"},
    "caribbean": {"bounds": (-87, 9, -60, 28), "type": "sea"},
    "north sea": {"bounds": (-4, 51, 9, 62), "type": "sea"},
    "baltic sea": {"bounds": (9, 53, 31, 66), "type": "sea"},
    "black sea": {"bounds": (27, 40, 43, 48), "type": "sea"},
    "coral sea": {"bounds": (142, -30, 165, -10), "type": "sea"},
    "tasman sea": {"bounds": (150, -50, 170, -25), "type": "sea"},
    "arafura sea": {"bounds": (130, -12, 142, -5), "type": "sea"},
    "timor sea": {"bounds": (124, -15, 135, -8), "type": "sea"},
    "great barrier reef": {"bounds": (142, -25, 154, -10), "type": "reef"},

    # Temperature-based regions
    "warm waters": {"bounds": (-180, -40, 180, 40), "type": "temperature"},
    "cold waters": {"bounds": [(-180, 40, 180, 90), (-180, -90, 180, -40)], "type": "temperature"},
    "cool waters": {"bounds": [(-180, 30, 180, 50), (-180, -50, 180, -30)], "type": "temperature"},

    # Depth-based (approximate coastal vs deep ocean)
    "coastal": {"bounds": (-180, -90, 180, 90), "type": "depth", "coastal": True},
    "offshore": {"bounds": (-180, -90, 180, 90), "type": "depth", "coastal": False},
    "deep sea": {"bounds": (-180, -90, 180, 90), "type": "depth", "coastal": False},
    "shallow waters": {"bounds": (-180, -90, 180, 90), "type": "depth", "coastal": True},

    # Add approximate bounding boxes for previously unmatched specific locations
    "southeast asia": {"bounds": [ (95, -15, 141, 10), (98, 6, 110, 20) ], "type": "regional"},
    "ryukyu islands": {"bounds": (122, 24, 131, 30), "type": "regional"},
    "northern australia": {"bounds": (113, -20, 138, -10), "type": "continental"},
    "indo-pacific ocean": {"bounds": [ (20, -50, 180, 30), (-180, -15, 20, 15) ], "type": "regional"},
    "north atlantic": {"bounds": (-80, 0, -20, 65), "type": "ocean"},
    "south atlantic": {"bounds": (-70, -60, 20, 0), "type": "ocean"},
    "north pacific": {"bounds": (120, 0, -120, 65), "type": "ocean"},
    "south pacific": {"bounds": (120, -60, -70, 0), "type": "ocean"},
    "central indian ocean": {"bounds": (60, -40, 100, 10), "type": "ocean"},
    "melanesia": {"bounds": (140, -15, 180, -5), "type": "island"},
    "micronesia": {"bounds": (130, 0, 160, 20), "type": "island"},
    "polynesia": {"bounds": (-150, -30, -110, 10), "type": "island"},
    "new zealand": {"bounds": (165, -48, 180, -33), "type": "country"},
    "hawaii": {"bounds": (-161, 18, -154, 23), "type": "island"},
    "galápagos islands": {"bounds": (-92, -2, -88, 2), "type": "island"},
    "maldives": {"bounds": (72, -1, 74, 8), "type": "island"},
    "sri lanka": {"bounds": (79, 5, 82, 10), "type": "island"},
    "andaman and nicobar islands": {"bounds": (92, 6, 94, 14), "type": "island"},
    "sulu sea": {"bounds": (119, 5, 123, 12), "type": "sea"},
    "celebes sea": {"bounds": (120, 0, 126, 7), "type": "sea"},
    "bismarck sea": {"bounds": (140, -5, 152, -1), "type": "sea"},
    "java sea": {"bounds": (105, -8, 116, -3), "type": "sea"},
    "banda sea": {"bounds": (123, -8, 133, 1), "type": "sea"},
    "philippine sea": {"bounds": (120, 5, 150, 25), "type": "sea"},
    "east africa": {"bounds": (-5, -15, 55, 15), "type": "region"},
    "west africa": {"bounds": (-20, -5, 15, 25), "type": "region"},
    "north africa": {"bounds": (-20, 15, 35, 38), "type": "region"},
    "central africa": {"bounds": (10, -10, 35, 10), "type": "region"},
    "southern africa": {"bounds": (10, -35, 35, -10), "type": "region"},
    "south asia": {"bounds": (60, 5, 95, 35), "type": "region"},
    "east asia": {"bounds": (95, 15, 145, 50), "type": "region"},
    "west asia": {"bounds": (30, 10, 75, 45), "type": "region"},
    "central asia": {"bounds": (50, 35, 85, 55), "type": "region"},
    "middle east": {"bounds": (30, 10, 60, 40), "type": "region"},

}


location_mapping = {
    # Major ocean regions
    "indo pacific": "indo-pacific",
    "indopacific": "indo-pacific",
    "indian pacific": "indo-pacific",
    "indian ocean pacific ocean": "indo-pacific",
    "western pacific ocean": "western pacific",
    "eastern pacific ocean": "eastern pacific",
    "northwest pacific": "northwestern pacific",
    "northeast pacific": "northeastern pacific",
    "southeast pacific": "southeastern pacific",
    "southwest pacific": "southwestern pacific",
    "central pacific": "central pacific",
    "north central pacific": "central pacific",
    "equatorial pacific": "central pacific",
    "eastern atlantic ocean": "eastern atlantic",
    "western atlantic ocean": "western atlantic",
    "southwest atlantic": "southwestern atlantic",
    "southeast atlantic": "southeastern atlantic",
    "northeast atlantic": "northeastern atlantic",
    "northwest atlantic": "northwestern atlantic",
    "south pacific": "southern pacific",
    "north pacific": "northern pacific",
    "south atlantic": "southern atlantic",
    "north atlantic": "northern atlantic",
    "atlantic ocean": "atlantic",
    "pacific ocean": "pacific",
    "indian ocean": "indian",
    "arctic ocean": "arctic",
    "antarctic ocean": "southern ocean",
    "southern ocean": "southern ocean",

    # Seas and regional waters
    "caribbean sea": "caribbean",
    "gulf of mexico": "gulf of mexico",
    "mediterranean sea": "mediterranean",
    "red sea": "red sea",
    "arabian sea": "arabian sea",
    "north sea": "north sea",
    "baltic sea": "baltic sea",
    "bering sea": "bering sea",
    "sargasso sea": "sargasso sea",
    "coral sea": "coral sea",
    "tasman sea": "tasman sea",
    "okhotsk sea": "sea of okhotsk",
    "sea of okhotsk": "sea of okhotsk",
    "south china sea": "south china",
    "east china sea": "east china",
    "yellow sea": "yellow sea",
    "sea of japan": "sea of japan",
    "japan sea": "sea of japan",

    # Biogeographic / ecological zones
    "tropical atlantic": "tropical atlantic",
    "temperate atlantic": "temperate atlantic",
    "tropical pacific": "tropical pacific",
    "temperate pacific": "temperate pacific",
    "subtropical pacific": "subtropical pacific",
    "subtropical atlantic": "subtropical atlantic",
    "tropical indian": "tropical indian",
    "temperate indian": "temperate indian",
    "subantarctic": "subantarctic",
    "antarctic": "antarctic",

    # Others
    "coastal regions": "coastal",
    "pelagic regions": "pelagic",
    "deep sea": "deep sea",
    "open ocean": "pelagic",
    "continental shelf": "continental shelf",

}
